# Smart Hyperparameter Search Configuration 
# Based on working small.yaml structure
working_dir_path: "results/smart_search"

problem:
  num_customers: 20
  vehicle_capacity: 30
  coord_range: 100
  demand_range: [1, 9]

training:
  num_instances: 4096     # More training data for statistical significance
  batch_size: 512         # Will be overridden by search
  num_epochs: 128         # Extended training for breakthrough search
  learning_rate: 1e-4     # Will be overridden by search
  validation_frequency: 8
  
# Advanced training parameters (will be overridden by search)
training_advanced:
  early_stopping_patience: 25
  temp_start: 5.0         # Will be overridden by search
  temp_min: 0.02          # Will be overridden by search  
  temp_adaptation_rate: 0.15  # Will be overridden by search
  use_adaptive_temperature: true

# Model architecture (will be dynamically overridden)
model:
  input_dim: 3             # Correct input dimension for CVRP (x, y, demand)
  hidden_dim: 128         # Will be overridden by embedding_dim search
  num_heads: 8            # Will be overridden by n_heads search
  num_layers: 4           # Will be overridden by n_layers search
  transformer_dropout: 0.1 # Will be overridden by dropout search
  feedforward_multiplier: 4
  edge_embedding_divisor: 8
  
# Cost configuration
cost:
  depot_penalty_per_visit: 0.0
  
# Logging
logging:
  level: INFO
  format: '%(message)s'
  
# Inference configuration
inference:
  default_temperature: 1.0
  greedy_evaluation: true
  max_steps_multiplier: 2
  attention_temperature_scaling: 0.5
  log_prob_epsilon: 1e-12
  masked_score_value: -1e9

# Experiment configuration
experiment:
  random_seed: 42
