# Debug config - Minimal settings for debugging
working_dir_path: "training_cpu/results/debug"

problem:
  num_customers: 10
  vehicle_capacity: 20

training:
  batches_per_epoch: 2         # Just 2 batches per epoch for quick testing
  batch_size: 8                # Very small batch size
  n_epochs: 2                  # Just 2 epochs

# Minimal model for debugging
model:
  hidden_dim: 96               # Divisible by 3 for temporal attention
  num_heads: 6                 # Must be divisible by num_scales (3)
  num_layers: 2                # Minimal layers

# Baseline settings - reduce evaluation batches
baseline:
  eval_batches: 1              # Just 1 batch for evaluation
  update_frequency: 1          # Update every epoch
  warmup_epochs: 0             # No warmup

# GAT-specific architecture
model_gat:
  gat_hidden_dim: 96
  gat_layers: 2
