# Medium config - N=20 customers
working_dir_path: "training_cpu/results/medium"

problem:
  num_customers: 20
  vehicle_capacity: 30

# Model scaling for N=20
model:
  hidden_dim: 256              # Use default hidden dim
  num_heads: 4
  num_layers: 4

# GAT-specific architecture for N=20
model_gat:
  gat_hidden_dim: 256
  gat_layers: 4
