# Medium-scale configuration for research experiments
# Balanced between speed and comprehensive evaluation

# =================================================================
# FREQUENTLY CHANGED PARAMETERS (Basic Problem & Training Settings)
# =================================================================

# Problem Settings - Medium scale for research
problem:
  num_customers: 50         # Fixed number of customers (excluding depot)
  vehicle_capacity: 40      # Integer capacity
  demand_range: [1, 10]     # Integer demands [min, max]
  coord_range: 100          # Coordinate range [0, coord_range] then normalized to unit square

# Training Configuration - Research-grade training  
training:
  num_instances: 5000       # Number of training instances
  batch_size: 16            # Batch size for training
  num_epochs: 50            # Number of training epochs
  learning_rate: 5e-4       # Base learning rate

# =================================================================
# LESS FREQUENTLY CHANGED PARAMETERS
# =================================================================

# Model Architecture - Shared by ALL model types
# These parameters are used by: Pointer+RL, GT-Greedy, GT+RL, DGT+RL, GAT+RL
model:
  hidden_dim: 128           # Hidden dimension for all models
  num_heads: 8              # Number of attention heads  
  num_layers: 4             # Number of transformer layers

# Advanced Training Configuration
training_advanced:
  gradient_clip_norm: 1.0   # Gradient clipping for stability
  
  # Learning rate schedule
  warmup_epochs: 10         # Linear warmup epochs before cosine decay
  min_lr: 1e-6              # Minimum LR at end of cosine schedule
    
  # Reinforcement Learning parameters
  entropy_coef: 0.01        # Initial entropy coefficient
  entropy_min: 0.0          # Minimum entropy coefficient
  temp_start: 1.5           # Initial sampling temperature
  temp_min: 0.2             # Minimum sampling temperature
