# Medium-scale configuration: research experiments
working_dir_path: "results/medium"

problem:
  num_customers: 30

training:
  num_instances: 10000
  batch_size: 32
  num_epochs: 50

# Keep penalty explicit if studying its effect; default to small value
cost:
  depot_penalty_per_visit: 0.0
