# Production-scale configuration: larger experiments
working_dir_path: "results/production"

problem:
  num_customers: 100

training:
  num_instances: 20000
  batch_size: 64
  num_epochs: 150
  learning_rate: 1e-4

# Production uses no depot penalty by default
cost:
  depot_penalty_per_visit: 0.0
