# Production-scale configuration: larger experiments
working_dir_path: "results/production"

problem:
  num_customers: 100

training:
  num_batches_per_epoch: 2  # 2 batches per epoch
  batch_size: 64
  num_epochs: 150
  learning_rate: 1e-4

# Production uses no depot penalty by default
cost:
  depot_penalty_per_visit: 0.0
