# Small config - N=10 customers with full training
working_dir_path: "training_cpu/results/small"

problem:
  num_customers: 10
  vehicle_capacity: 30

model:
  hidden_dim: 128              # Reduced from default 256
  num_heads: 4                 
  num_layers: 3                # Shallower for small problems


