# Small-scale configuration: quick experiments overriding only study-relevant params
working_dir_path: "results/small"

problem:
  num_customers: 15

training:
  num_instances: 1024
  batch_size: 128
  num_epochs: 16

# Keep default cost penalty modest to speed learning signal; override if studying penalties
cost:
  depot_penalty_per_visit: 0.0
