baseline:
  eval_batches: 5
  update:
    frequency: 2
    warmup_epochs: 0
inference:
  default_temperature: 2.5
  max_steps_multiplier: 10
model:
  hidden_dim: 128
  num_heads: 4
  num_layers: 3
problem:
  num_customers: 10
  vehicle_capacity: 30
training:
  batch_size: 512
  num_batches_per_epoch: 50
  num_epochs: 2
training_advanced:
  compile:
    enabled: true
    mode: default
working_dir_path: ../results/tiny_gpu_512
