# Small-fast config to test GAT+RL
working_dir_path: "results/tiny_test"

problem:
  num_customers: 7

training:
  num_instances: 131072     
  batch_size: 512         
  num_epochs: 64          
  learning_rate: 0.0001 
  validation_frequency: 4

# Use mean baseline instead of rollout
baseline:
  type: mean

# Override for better algorithm differentiation
training_advanced:
  # Longer patience for better convergence
  early_stopping_patience: 25
  
  # More aggressive temperature adaptation for clear differences  
  temp_start: 3.5          # Even higher start
  temp_min: 0.05           # Even lower min
  temp_adaptation_rate: 0.25   # Faster adaptation

# Keep default cost penalty modest to speed learning signal
cost:
  depot_penalty_per_visit: 0.0
