# GPU-optimized tiny config with your specifications
working_dir_path: "../results/tiny_gpu_optimized"

problem:
  num_customers: 10
  vehicle_capacity: 20

training:
  num_batches_per_epoch: 25   # Reduced from 150 since batch_size increased
  batch_size: 4096            # 8x larger to use GPU memory
  num_epochs: 60

model:
  hidden_dim: 128
  num_heads: 4
  num_layers: 3

model_gat:
  gat_hidden_dim: 128
  gat_layers: 3

# Optimized baseline settings
baseline:
  type: "rollout"
  eval_batches: 2           # Reduced from 5
  update:
    enabled: true
    frequency: 2            # Update every 2 epochs instead of 1
    significance_test: true
    p_value: 0.10

# Experiment settings
experiment:
  random_seed: 42
  device: "cuda"
  use_advanced_features: true
  strict_validation: false  # Disabled for speed

# GPU-specific optimizations
gpu:
  device: cuda:0
  enabled: true
  gradient_accumulation_steps: 1
  memory_fraction: 0.95
  mixed_precision: false    # Disabled for small N=10
  non_blocking: true
  num_workers: 0
  pin_memory: false
  prefetch_factor: 2
