# Tiny config - Quick experiments with reduced training
# Same problem as small (N=10) but reduced training data
working_dir_path: "training_cpu/results/tiny"

problem:
  num_customers: 10
  vehicle_capacity: 20

training:
  batches_per_epoch: 10        # Much smaller for quick testing
  batch_size: 64               # Reasonable batch size
  n_epochs: 5                  # Few epochs for testing
  baseline:                    # Baseline config must be nested under training
    eval_batches: 2            # Small number for quick evaluation
    update_frequency: 2        # Update every 2 epochs
    warmup_epochs: 0           # No warmup for quick testing

# Smaller model for faster training
model:
  hidden_dim: 128              # Half of default 256
  num_heads: 4
  num_layers: 3                # Reduced from default 4

# GAT-specific architecture for tiny experiments
model_gat:
  gat_hidden_dim: 128          # Smaller for quick experiments
  gat_layers: 3                # Fewer layers for speed
