# Tiny config for n=20 - Quick experiments with 20 customers
working_dir_path: "../results/tiny_2_n20"

problem:
  num_customers: 20
  vehicle_capacity: 30

training:
  num_batches_per_epoch: 25   # Paper's scale: 768,000 instances per epoch
  batch_size: 128             # Default batch size (paper's value)
  num_epochs: 10              # Default number of epochs

# Smaller model for faster training
model:
  hidden_dim: 128              # Half of default 256
  num_heads: 4
  num_layers: 3                # Reduced from default 4

# GAT-specific architecture for tiny experiments
model_gat:
  gat_hidden_dim: 128          # Smaller for quick experiments
  gat_layers: 3                # Fewer layers for speed
